version: 2.1

jobs:
  lint:
    docker:
      - image: 'cimg/go:1.18'
    working_directory: ~/lint
    steps:
      - checkout
      - run:
          name: 'Enforce Go minimal dependencies (Tidy) Code'
          command: go mod tidy && git diff --exit-code -- go.mod go.sum
      - run:
          name: 'YOU FAILED GO FMT, PLEASE RUN go fmt ./... on your repo (make sure you use go version 1.18)'
          command: 'echo "YOU FAILED GO FMT, PLEASE RUN go fmt ./... on your repo (make sure you use go version 1.18)"'
          when: on_fail
      - run:
          name: Enforce Go Formatted Code
          command: exit $(go fmt ./...)
      - run:
          name: Run basic code analysis
          command: exit $(go vet ./...)
  test:
    docker:
      - image: 'cimg/go:1.18'
    working_directory: ~/go-api
    steps:
      - checkout
      - run:
          name: 'Run tests'
          command: 'go test -v -covermode=count -coverpkg=./...  ./...'


workflows:
  tests:
    jobs:
      - lint
      - test
